#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --job-name=fastqc
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --error=%x-%J-%u.err
#SBATCH --output=%x-%J-%u.out

module --force purge
ml biocontainers fastqc

INPUT_DIR="$SCRATCH/RNAseq/mdg_017_R_S41_L004"
SAMPLE_R1="$INPUT_DIR/clean.R1.fq.gz"
SAMPLE_R2="$INPUT_DIR/clean.R2.fq.gz"
SCRATCH_DIR="$SCRATCH/RNAseq"
OUT_DIR="$SCRATCH_DIR/fastqc_out"

fastqc "$SAMPLE_R1" "$SAMPLE_R2" --outdir "$OUT_DIR" 

fastqc -o fastqc_out -t 4 FASTQ1 FASTQ2
